services:
  app:
    build: ./backend
    container_name: kubeflow-demo_api
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost
    depends_on:
      - weaviate
    volumes:
      - ./backend:/app 
    command: ["sh", "-c", "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kubeflow-demo_frontend
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://localhost:8000
    env_file:
      - ./frontend/.env

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate-data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate-data:
    driver: local